INSERT INTO LIBRARY(NAME, LOCATION, MEMBERS, MEMBERSHIP_FEE, LATE_FEE_PER_DAY)
VALUES ("TEST NAME", "TEST", 100, 10.0, 0.1);

INSERT INTO LIBRARY(NAME, LOCATION, MEMBERS, MEMBERSHIP_FEE, LATE_FEE_PER_DAY)
VALUES ("TEST NAME1", "TEST", 110, 11.0, 0.2);